### PR TITLE
Fixes #10 feat, adds cleanup-method implementation 

### LINKED ISSUE #10: Implement `cleanup` method
Implement a method that cleans up and deletes the build files.

### PR DESCRIPTION
**Pull request by jonassavas**
Fixes #10 feat, adds cleanup-method implementation to completely remove the 'target' directory once the server has built/tested the system under test.

### CODE REVIEW

**Review by FalkWasTaken — COMMENTED** [review]
Looks good! However, I think it could be convenient to have a dedicated method to clean the target directory. Perhaps create another signature of the `cleanup` method without any parameters that deletes the target directory?

**Comment by jonassavas** [comment]
I agree, it should be fixed now!

**Review by FalkWasTaken — CHANGES_REQUESTED** [review]
The new method looks good but the main method is now out-commented.

**Comment by jonassavas** [comment]
Removed now! needed to isolate the test without starting the server

**Review by FalkWasTaken — APPROVED** [review]
Looks good!

**Pull request merged**
